### PR TITLE
fix(daemon): Use "balanced" for acpi-platform balanced setting

### LINKED ISSUE #330: Can't switch to balanced acpi mode on lenovo yoga slim 7 pro 14ACH5 laptop
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-power:
  Installed: 1.1.20~1648241921~22.04~1e1599a
  Candidate: 1.1.20~1648241921~22.04~1e1599a
  Version table:
 *** 1.1.20~1648241921~22.04~1e1599a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Kernel (`uname -rv`):**
```
5.16.15-76051615-generic #202203161444~1647964027~22.04~e706226 SMP PREEMPT Tue Mar 22 17
```

**Issue/Bug Description:**
When selecting the Balanced mode, my laptop stays in the previous mode. I believe this is because of the difference in the balance mode name. [Current code](https://github.com/pop-os/system76-power/blob/1e1599a9dd1208820fcb2e374fea9f72b35e50e7/src/acpi_platform.rs#L25=) tries to set it to `balanced-performance`. When I run `cat /sys/firmware/acpi/platform_profile_choices` I get:
```
low-power balanced performance
```

So for my laptop there is no `balanced-performance` mode. It should be called `balanced`.

**Expected behavior:**
ACPI mode switching code should use the available profile name. I have not checked if `platform_profile_choices` is the official/documented way to list available modes.

**Other Notes:**
THANK YOU for you work on Pop!_OS !!! I love how your distribution is shaping up, I am glad I have "ubuntu" without snaps on my system, and how everything just works!
(I will probably stay with the 5.16 kernel if that will be possible because recent patches to 5.17 [might disable](https://www.phoronix.com/forums/forum/software/mobile-linux/1306103-lenovo-s-platform-profile-support-for-amd-systems-on-linux-has-been-busted?p=1306739#post1306739) the power switching on my laptop because it was doing nothing for some other similar AMD models, hopefully they will fix for 5.18 and enable it back)

### PR DESCRIPTION
**Pull request by mmstick**
Closes #330

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

File: src/acpi_platform.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ pub fn battery() {
 }
 
 pub fn balanced() {
-    if let Err(why) = fs::write(SYSFS_PATH, "balanced-performance") {
+    if let Err(why) = fs::write(SYSFS_PATH, "balanced") {
         eprintln!("ACPI Platform Profile: could not set to balanced-performance: {}", why);
```
Comment (crawfxrd) [inline src/acpi_platform.rs:26]: Error message needs to be updated as well.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
As mentioned in https://github.com/pop-os/system76-power/pull/278, only Lenovo products currently support acpi/platform_profile, so I can't verify whether https://github.com/pop-os/system76-power/issues/330 is working.

Power profiles still switch as expected on System76 hardware. Log output in journalctl is as expected when switching profiles, cpufreq/scaling_governor is still set as expected, screen brightness is still set as expected.
